version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "targety-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eb3jza5nuwcg"
s3_prefix = "targety-test"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
