AWSTemplateFormatVersion: 2010-09-09
Description: >-
    example-function

Transform:
    - AWS::Serverless-2016-10-31

Resources:
    TargetyExampleFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: dist/index.handler
            Runtime: nodejs14.x
            MemorySize: 128
            Timeout: 100
            Description: An example function
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /test
                        Method: GET
Outputs:
    WebEndpoint:
        Description: "API Gateway endpoint URL for Prod stage"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
